name: Dispatch Fuzz

on:
  workflow_dispatch:

jobs:
  run-fuzz:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v2
        with:
          python-version: '3.8'

      - name: Run fuzz.py
        run: python FAME_ML/fuzz.py

      - name: Upload fuzz results
        uses: actions/upload-artifact@v4
        with:
          name: fuzz_results
          path: 'FAME_ML/fuzz_results.txt'